### ISSUE TITLE
Ties?

### ISSUE THREAD

**Issue by TekEffekt** [aturingmachine/init-tracker#1]
I wana resolve ties in initiative plz

**Comment by TekEffekt** [comment]
@aturingmachine Any progress on this issue Mr. maintainer? I'm a random person on the internet and I'd like you to do more free work on this project. Specifically the free work that I want

**Comment by aturingmachine** [comment]
The work I do that pays me has been taking precedence, we're you looking to use this during an upcoming DND session this weekend perhaps?

**Comment by TekEffekt** [comment]
Perhaps, yes........

**Comment by aturingmachine** [comment]
I can't promise this will be in by then, you can feel free to pick it up if you like.

**Comment by aturingmachine** [comment]
Should be solved as of 1f3f3e5. Lemme know if you need something more.
